In [1]:
import numpy as np

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [2]:
x[-1] = 5
x

array([1, 2, 3, 5])

In [4]:
# Trying to access an index that doesn't exist will throw an error.

x[4] = 10

IndexError: index 4 is out of bounds for axis 0 with size 4

In [5]:
arr = np.array([1, 2, 'coconut'])
arr

array(['1', '2', 'coconut'], dtype='<U21')

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
arr = np.array([1, 2, 3])
print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [11]:
arr.shape

(3,)

In [12]:
arr.ndim

1

In [13]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
arr_3d = np.array([[[1, 2, 3],
                   [3, 4, 5]],

                  [[5, 6, 7],
                   [7, 8, 9]]]
)

print(arr_3d.shape)
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [15]:
arr_2d = arr_2d.reshape(2, 4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr = np.array([1, 2, 3, 4, 5])

np.mean(arr)

np.float64(3.0)

In [17]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [18]:
np.floor(5.7)

np.float64(5.0)

In [ ]:
np.ceil(5.3)

np.float64(6.0)

: 