In [1]:
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [2]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

In [3]:

np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [5]:

np.full((5, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [6]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [7]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, 2)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, -1)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.tolist()

[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

In [10]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a.max())
print(a.mean())
print(a.min())
print(a.std())

[[1 2 3]
 [4 5 6]]

6
3.5
1
1.707825127659933


In [11]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()

print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

[[1 2 3]
 [4 5 6]]

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [12]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a[1])
print(a[0, 1])
print(a[1, 2])

[[1 2 3]
 [4 5 6]]

[4 5 6]
2
6


In [13]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

a[:, 1:]

[[1 2 3]
 [4 5 6]]



array([[2, 3],
       [5, 6]])

In [14]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])
print('a:')
print(a)
print()
print('b:')
print(b)
print()
print('a + b:')
print(a + b)
print()
print('a * b:')
print(a * b)

a:
[[1 2 3]
 [4 5 6]]

b:
[[1 2 3]
 [1 2 3]]

a + b:
[[2 4 6]
 [5 7 9]]

a * b:
[[ 1  4  9]
 [ 4 10 18]]


In [15]:
a = np.array([(1, 2), (3, 4)])
print(a)
print()

a[1][1] = 100
a

[[1 2]
 [3 4]]



array([[  1,   2],
       [  3, 100]])

In [16]:
# However, the array cannot be lengthened or shortened:


a = np.array([1, 2, 3])
print(a)
print()

a[3] = 100
a

[1 2 3]



IndexError: index 3 is out of bounds for axis 0 with size 3